### ISSUE TITLE
В методе upload_photo вызывается photo.getMessageUploadServer с type=audio_message

### ISSUE THREAD

**Issue by kiriharu** [undefinedvalue0103/pylibs#1]
![image](https://user-images.githubusercontent.com/38693046/51121343-4b253980-1828-11e9-971f-5f7c37b45ce6.png)
Я думаю, что это опечатка. Исправьте, пожалуйста, если я был прав.

**Comment by undefinedvalue0103** [comment]
Да, вы правы, просто изначально был написан только метод "upload_voice", который копировался. Я просто забыл удалить параметр "type", но на работу это не влияло. В любом случае, я уже исправил.

Спасибо за замечание
